-- MySQL Script generated by MySQL Workbench
-- Mon Jan 25 10:50:32 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `blog` ;

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blog` DEFAULT CHARACTER SET utf8 ;
USE `blog` ;

-- -----------------------------------------------------
-- Table `blog`.`author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`author` ;

CREATE TABLE IF NOT EXISTS `blog`.`author` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `nickname` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `pseudo_UNIQUE` ON `blog`.`author` (`nickname` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `blog`.`articles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`articles` ;

CREATE TABLE IF NOT EXISTS `blog`.`articles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title_article` VARCHAR(45) NOT NULL,
  `text_article` VARCHAR(150) NOT NULL,
  `publication_date` DATETIME NOT NULL,
  `publication_enddate` DATETIME NOT NULL,
  `importance` INT NOT NULL DEFAULT 0,
  `author_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_articles_author1`
    FOREIGN KEY (`author_id`)
    REFERENCES `blog`.`author` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_articles_author1_idx` ON `blog`.`articles` (`author_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `blog`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`categories` ;

CREATE TABLE IF NOT EXISTS `blog`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `categories_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`commentaries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`commentaries` ;

CREATE TABLE IF NOT EXISTS `blog`.`commentaries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text_commentary` VARCHAR(150) NOT NULL,
  `date` DATETIME NOT NULL DEFAULT now(),
  `author_id` INT NOT NULL,
  `articles_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_commentaries_author1`
    FOREIGN KEY (`author_id`)
    REFERENCES `blog`.`author` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commentaries_articles1`
    FOREIGN KEY (`articles_id`)
    REFERENCES `blog`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_commentaries_author1_idx` ON `blog`.`commentaries` (`author_id` ASC) VISIBLE;

CREATE INDEX `fk_commentaries_articles1_idx` ON `blog`.`commentaries` (`articles_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `blog`.`articles_has_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`articles_has_categories` ;

CREATE TABLE IF NOT EXISTS `blog`.`articles_has_categories` (
  `articles_id` INT NOT NULL,
  `categories_id` INT NOT NULL,
  PRIMARY KEY (`articles_id`, `categories_id`),
  CONSTRAINT `fk_articles_has_categories_articles1`
    FOREIGN KEY (`articles_id`)
    REFERENCES `blog`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articles_has_categories_categories1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `blog`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_articles_has_categories_categories1_idx` ON `blog`.`articles_has_categories` (`categories_id` ASC) VISIBLE;

CREATE INDEX `fk_articles_has_categories_articles1_idx` ON `blog`.`articles_has_categories` (`articles_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
